language: cpp
compiler:
  - gcc
  - clang
script:
  - ./autogen.sh
  - ./configure --prefix /tmp/mjwm
  - make -j4
  - make check -j4
  - make install-strip
  - ls -halR /tmp/mjwm
  - ./test_runner.sh
  - time /tmp/mjwm/bin/mjwm
  - cat automenu
