language: cpp
compiler:
  - gcc
  - clang
script:
  - ./autogen.sh
  - ./configure
  - make check
  - ./test_runner.sh
  - echo $XDG_DATA_DIRS
  - echo $XDG_DATA_HOME
  - time ./mjwm -i /usr/share/applications
  - cat automenu
