language: cpp
compiler:
  - gcc
  - clang
script:
  - ./autogen.sh
  - ./configure --prefix /tmp/mjwm
  - make -j4
  - make check -j4
  - ./test_runner.sh
  - make install-strip
  - ls -halR /tmp/mjwm
  - time /tmp/mjwm/bin/mjwm -o automenu.default
  - cat automenu.default
  - time /tmp/mjwm/bin/mjwm --iconize  -o automenu.iconize
  - cat automenu.iconize
