language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install lcov
  - # sudo pip install cpp-coveralls
script:
  - ./autogen.sh
  - ./coverage.sh
  - make install-strip && ls -halR /tmp/amm
  - time /tmp/amm/bin/amm -o automenu.default && cat automenu.default
  - time /tmp/amm/bin/amm --iconize -o automenu.iconize && cat automenu.iconize
