language: cpp
compiler:
  - gcc
  - clang
script:
  - ./autogen.sh
  - ./configure --prefix /tmp/mjwm
  - make check
  - ./test_runner.sh
  - time ./mjwm
  - cat automenu
  - make install
  - ls -halR /tmp/mjwm
