language: cpp
compiler:
  - gcc
  - clang
script:
  - aclocal -I .
  - autoheader -I .
  - automake --add-missing --copy --gnu
  - autoconf
  - ./configure
  - make check
  - ./test_runner.sh
  - time ./mjwm
  - cat automenu
